CONFIG_STDOUT_CONSOLE=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_PRINTK=y
CONFIG_EARLY_CONSOLE=y

#USB related configs
CONFIG_USB_DEVICE_STACK=y
CONFIG_DEPRECATION_TEST=y
CONFIG_USB_DEVICE_PRODUCT="VapeLogger Audio"
CONFIG_USB_DEVICE_VID=0x239A
CONFIG_USB_DEVICE_PID=0x810E
CONFIG_USB_DEVICE_MANUFACTURER="VapeLogger"
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y
CONFIG_USB_DEVICE_STACK_NEXT=n

#LOG subsystem related configs
CONFIG_LOG=y
CONFIG_USB_DRIVER_LOG_LEVEL_ERR=y
CONFIG_USB_DEVICE_LOG_LEVEL_ERR=y

#net buf options
CONFIG_NET_BUF=y

#USB audio related configs
CONFIG_USB_DEVICE_AUDIO=y

#Audio and DMIC configs
CONFIG_AUDIO=y
CONFIG_AUDIO_DMIC=y

# ADC for coil monitoring
CONFIG_ADC=y
CONFIG_ADC_NRFX_SAADC=y
